[package]
authors = ["Samuel Laur√©n <samuel.lauren@iki.fi>"]
build = "build.rs"
license = "GPL-3.0"
name = "process-queue"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "pqueue"
path = "src/main.rs"

[build-dependencies]
clap = "2.20.3"

[dependencies]
clap = "2.20.3"
daemonize = "0.2.3"
dbus = "0.5.0"
env_logger = "0.4.0"
log = "0.3.6"
regex = "0.2.1"
users = "0.5.2"
xdg = "2.0.0"
